package com.agentstorage.copilot.data.remote

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import java.io.IOException
import java.util.concurrent.TimeUnit

class GeminiApiClient {

    private val json = Json {
        ignoreUnknownKeys = true
        isLenient = true
    }

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(90, TimeUnit.SECONDS) // 90-second read timeout for complex reasoning
        .writeTimeout(30, TimeUnit.SECONDS)
        .build()

    /**
     * Stateless call to Gemini API using pre-flight sanitized contents.
     */
    suspend fun generateActionPlan(
        apiKey: String,
        model: String = "gemini-2.5-flash",
        systemPrompt: String,
        userPrompt: String
    ): String = withContext(Dispatchers.IO) {
        val endpoint = "https://generativelanguage.googleapis.com/v1beta/models/$model:generateContent?key=$apiKey"

        val requestPayload = GeminiRequest(
            systemInstruction = GeminiContent(parts = listOf(GeminiPart(text = systemPrompt))),
            contents = listOf(
                GeminiContent(role = "user", parts = listOf(GeminiPart(text = userPrompt)))
            ),
            generationConfig = GeminiGenerationConfig(temperature = 0.2f)
        )

        val requestBody = json.encodeToString(requestPayload)
            .toRequestBody("application/json; charset=utf-8".toMediaType())

        val request = Request.Builder()
            .url(endpoint)
            .post(requestBody)
            .build()

        val response = okHttpClient.newCall(request).execute()
        if (!response.isSuccessful) {
            val errorBody = response.body?.string() ?: "Empty error response"
            throw IOException("Gemini API error (HTTP ${response.code}): $errorBody")
        }

        val responseBody = response.body?.string() ?: throw IOException("Empty response from Gemini")
        val parsed = json.decodeFromString<GeminiResponse>(responseBody)

        val candidateText = parsed.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
            ?: throw IOException("No candidate response generated by model.")

        candidateText
    }
}
