package com.agentstorage.copilot.data.remote

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import java.io.IOException
import java.util.concurrent.TimeUnit

class GeminiApiClient {

    companion object {
        const val DEFAULT_MODEL = "gemini-2.5-flash"
        const val FALLBACK_MODEL = "gemini-3.5-flash-lite"
    }

    private val json = Json {
        ignoreUnknownKeys = true
        isLenient = true
    }

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(90, TimeUnit.SECONDS) // 90-second read timeout for complex reasoning
        .writeTimeout(30, TimeUnit.SECONDS)
        .build()

    /**
     * Stateless call to Gemini API using pre-flight sanitized contents.
     */
    suspend fun generateActionPlan(
        apiKey: String,
        model: String = DEFAULT_MODEL,
        systemPrompt: String,
        userPrompt: String
    ): String = withContext(Dispatchers.IO) {
        val candidateModels = if (model != FALLBACK_MODEL) {
            listOf(model, FALLBACK_MODEL)
        } else {
            listOf(model)
        }

        var lastException: IOException? = null

        for (activeModel in candidateModels) {
            val endpoint = "https://generativelanguage.googleapis.com/v1beta/models/$activeModel:generateContent?key=$apiKey"

            val requestPayload = GeminiRequest(
                systemInstruction = GeminiContent(parts = listOf(GeminiPart(text = systemPrompt))),
                contents = listOf(
                    GeminiContent(role = "user", parts = listOf(GeminiPart(text = userPrompt)))
                ),
                generationConfig = GeminiGenerationConfig(temperature = 0.2f)
            )

            val requestBody = json.encodeToString(requestPayload)
                .toRequestBody("application/json; charset=utf-8".toMediaType())

            val request = Request.Builder()
                .url(endpoint)
                .post(requestBody)
                .build()

            try {
                val response = okHttpClient.newCall(request).execute()
                if (!response.isSuccessful) {
                    val errorBody = response.body?.string() ?: "Empty error response"
                    if (response.code == 404 && activeModel != candidateModels.last()) {
                        // Model 404 Not Found - attempt fallback model
                        continue
                    }
                    throw IOException("Gemini API error (HTTP ${response.code}): $errorBody")
                }

                val responseBody = response.body?.string() ?: throw IOException("Empty response from Gemini")
                val parsed = json.decodeFromString<GeminiResponse>(responseBody)

                val candidateText = parsed.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                    ?: throw IOException("No candidate response generated by model.")

                return@withContext candidateText
            } catch (e: IOException) {
                lastException = e
                if (activeModel == candidateModels.last()) {
                    throw e
                }
            }
        }

        throw lastException ?: IOException("Failed to generate content with model $model")
    }
}
